### ISSUE TITLE
Possible to include sources as source jar ?

### ISSUE THREAD

**Issue by thibaultmeyer** [martinpaljak/oracle_javacard_sdks#1]
Hello,

Is it possible to add javacard-xxxx-sources.jar (generated from preprocessed_src folder) to allow IDE to have a valid auto-completion and show real method argument names and description ?

Sincerly

**Comment by martinpaljak** [comment]
The idea of this repository is to provide a verbatim copy (possibly only reduced for size matters) of Oracle JavaCard SDK-s. Anything extra should be justified (I can understand this reason, though).

If you provide a patch (for a makefile or such) it could be considered, though.

**Comment by martinpaljak** [comment]
Closing as stale.
